### ISSUE TITLE
Play around and add some todo CRUD

### ISSUE THREAD

**Issue by shiningflint** [shiningflint/rails_docker_test#6]
Now just play around to add some features with different branch and deployment directly with ssh.
- [ ] Create a feature branch and develop the todos CRUD there
- [ ] Deploy the feature branch to the ubuntu server
- [ ] Revert back to master branch and deploy the master branch
- [ ] Merge the feature branch and redeploy the updated master branch
